### ISSUE TITLE
[原版本] 文件上传组件可用于XSS攻击

### ISSUE THREAD

**Issue by zrquan** [wkeyuan/DWSurvey#104]
问卷使用的文件上传组件只会在前端检测文件后缀，用户可以直接修改请求中的filename和mime type来上传html文件
![Screenshot_20230414_143909](https://user-images.githubusercontent.com/33086594/231964299-18b2d810-cb30-4144-acac-3b37849329e8.png)

管理员查看问卷的原始数据时如果打开了html文件就会遭到XSS攻击，虽然cookie设置了httponly不能直接窃取，还是可以利用同域发起CSRF攻击。比如创建用户：
![Screenshot_20230414_145656](https://user-images.githubusercontent.com/33086594/231967507-4c4fdec4-5b47-4f8d-9fc7-5ff23a4bd069.png)

**Comment by easyandeasy** [comment]
.....

**Comment by wkeyuan** [comment]
@zrquan  感谢你的反馈，收到反馈后我们已经第一时间作出修改，这个问题应该早就被修复，在我们其它产品与项目里面都有处理，由于自己平时工作太多，就把这事给忘了，再次感谢你的反馈，欢迎继续指出问题。

**Comment by zrquan** [comment]
@wkeyuan 我在Q群提供的社区版（dwsurvey-oss-vue-v.5.3.0-Beta.jar）和“原版本”体验地址（https://ent.surveyform.cn/）上验证过是还可以利用的，所以应该还是有点风险，新版本确实没有这个问题

**Comment by wkeyuan** [comment]
@zrquan 是的，Q群v.5.3.0是老版本，已经发布最新v.5.4.0到Q群。
