### ISSUE TITLE
选择题（单选和多选），选中某项后可填空功能未实现

### ISSUE THREAD

**Issue by ELE-Clouds** [wkeyuan/DWSurvey#12]
在设置选择题（无论是单选还是多选）时，设置了某一项为选中后可填空，设置完成后，当前项后面已经显示了一个输入框，但在提交发布后，实际使用时，选中该项，并未出现输入框。无法进行输入。

**Comment by wkeyuan** [comment]
这个问题应该是已经解决过了
<img width="731" alt="qq20170716-0 2x" src="https://user-images.githubusercontent.com/19662469/28248789-078431a4-6a7d-11e7-9aca-8688c4c6600f.png">
