### ISSUE TITLE
发现2个bug

### ISSUE THREAD

**Issue by Enoch119** [wkeyuan/DWSurvey#5]
1.选择题后，选择选项后填空，在问卷设计中有出现输入框，但是在发布后没有效果。
2.问卷停止收集后，电脑端是无法回答了,手机用二维码还是能回答问题。

**Comment by wkeyuan** [comment]
除移动端输入框还没有想好怎么加外，其它问题已经基本修复。

**Comment by wkeyuan** [comment]
移动端也支持了
