### ISSUE TITLE
xssprotest、spssw、ueditor 这三个jar包下载不了

### ISSUE THREAD

**Issue by cumtgujun** [wkeyuan/DWSurvey#60]
xssprotest、spssw、ueditor 这三个jar包下载不了
http://maven.dwsurvey.net:8081/repository/maven-public/ 也用不了呢

**Comment by cdoer** [comment]
直接在pom文件注释掉，删掉com/key/common/plugs/spss  这个包就能运行，代码里面并没有用到这三个jar的代码

**Comment by viaco2ove** [comment]
ueditor 换成这两个可以吗？	 
<dependency>
			<groupId>com.baidu.ueditor</groupId>
			<artifactId>ueditor</artifactId>
			<version>1.1.1</version>
		</dependency>

		<dependency>
			<groupId>com.gitee.qdbp.thirdparty</groupId>
			<artifactId>ueditor</artifactId>
			<version>1.4.3.3</version>
		</dependency>

**Comment by XiLingNote** [comment]
注释掉代码和pom引用的jar可行的

**Comment by wkeyuan** [comment]
最新版本已经解决
