### ISSUE TITLE
`t_survey_detail`表中的`survey_note`建议改为`text`类型

### ISSUE THREAD

**Issue by StephenPCG** [wkeyuan/DWSurvey#7]
建议将 `t_survey_detail` 表中的 `survey_note` 改为 `text` 类型。`varchar(255)` 字数太少了。

**Comment by wkeyuan** [comment]
谢谢你的提醒，重新生成数据表时没有注意到这个问题，需要调整不止这一处，我会加一个更新sql上来。

**Comment by wkeyuan** [comment]
ALTER TABLE `dwsurvey`.`t_question` 
CHANGE COLUMN `qu_note` `qu_note` TEXT NULL DEFAULT NULL ,
CHANGE COLUMN `qu_title` `qu_title` TEXT NULL DEFAULT NULL ;
ALTER TABLE `dwsurvey`.`t_survey_detail` 
CHANGE COLUMN `survey_note` `survey_note` TEXT NULL DEFAULT NULL ;
