### ISSUE TITLE
出个springboot版本吧，技术栈也太老了

### ISSUE THREAD

**Issue by wujunshen** [wkeyuan/DWSurvey#73]
感觉除了前端界面还有点价值，后端java源码是在太out了。话说都2021年了，还ssh啊

**Comment by Just4test** [comment]
4年前的代码要什么自行车。

人家有springboot的版本，自己去官网买吧。

**Comment by wkeyuan** [comment]
已经升级到Vue，主要是做的比较早，前后快10年了，现在来看很多写法也有待优化，后面将持续优化

**Comment by javahuang** [comment]
> 已经升级到Vue，主要是做的比较早，前后快10年了，现在来看很多写法也有待优化，后面将持续优化

给老哥的坚持点个赞，开源不易，之前不该在这给 SK 推广的，抱歉。

**Comment by wkeyuan** [comment]
嗯，谢谢理解，等有空再来把之前的代码优化一下，让大家更容易理解些。

一件事情做久了，就没有办法放下，也是对大家的负责，希望自己能一直坚持下去吧，有空欢迎多多交流。
