### ISSUE TITLE
遇到乱码问题无法解决的同学看一下这里

### ISSUE THREAD

**Issue by SupritYoung** [wkeyuan/DWSurvey#82]
解决了一整天，看了几乎全网的文章，总结成一篇：
https://suprit.blog.csdn.net/article/details/119806501

**Comment by wkeyuan** [comment]
是的，根本原因就是静态文件通过tomcat服务时，应该是tomcat读取的时候编码不一致也术是JVM，所以返回给浏览器终端时就会是乱码状态。
现在可以使用最新基于Spring Boot + Vue 版本，这个应该可以彻底解决，因为启动时可以设置  -Dfile.encoding=utf-8 参数指令
